/* eslint-disable linebreak-style */
export class Language {
  constructor() {
    this.mainModalEnglish = ["Poker", "Menu", "New game", "Save game", "Load game", "Settings", "Rules"];
    this.mainModalRussia = ["Покер", "Меню", "Новая игра", "Сохранить", "Загрузить", "Настройки", "Правила"];
    this.settingsModalEnglish = ["Poker", "Settings", "Players:", "Language:", "Sound:", "Color:", "Apply", "Back"];
    this.settingsModalRussia = ["Покер", "Настройки", "Игроки:", "Язык:", "Звук:", "Цвет:", "Применить", "Вернуться"];
    this.rulesModalEnglish = ["Poker", "Rules", "The game can be played by one to four people. Players take turns. A player's turn consists of three dice rolls. After each throw, the player chooses which dice to keep and which to throw in order to improve his combination. At the end of the turn, the player writes down the collected combination in one of the remaining rows of the table. After twelve moves, the player with the most points wins.\n\nCombinations:\n\nOne: the sum of all collected ones. For example: 1-1-2-3-4 = 2.\n\nTwo: the sum of all collected twos. For example: 2-2-2-6-6 = 6.\n\nThree: the sum of all collected threes. For example: 3-3-1-2-4 = 6.\n\nFour: the sum of all collected fours. For example: 4-4-4-5-6 = 12.\n\nFive: the sum of all collected fives. For example: 5-5-1-2-3 = 10.\n\nSix: the sum of all collected sixes. For example: 6-6-6-1-2 = 18.\n\nAny: the sum of all dice, regardless of possible combinations. For example: 1-3-3-5-6 = 18.\n\nShort street: four dice in order. The combination is worth 25 points. For example: 1-2-3-4-1.\n\nLong Street: five dice in order. The combination is worth 30 points. For example: 2-3-4-5-6.\n\nFull House: two dice of one rank and three dice of another rank. The result will be the sum of all dice. For example: 2-2-3-3-3 = 13.\n\nFour of a kind: four dice of the same rank. The result will be the sum of all dice. For example: 5-5-5-5-1 = 21.\n\nPoker: five dice of the same rank. The combination is worth 50 points. For example: 1-1-1-1-1.", "Back"];
    this.rulesModalRussia = ["Покер", "Правила", "В игре могут участвовать от одного до четырех человек. Игроки ходят по очереди. Ход игрока состоит из трех бросков костей. После каждого броска игрок выбирает, какие кости оставить, а какие перебросить, что бы улучшить свою комбинацию. В конце хода игрок записывает собранную комбинацию в одну из оставшихся строчек таблицы. По истечении двенадцати ходов выигрывает игрок, набравший больше всего очков. \n\nКомбинации:\n\nЕдиницы: сумма всех собранных единиц. Например: 1-1-2-3-4 = 2.\n\nДвойки: сумма всех собранных двоек. Например: 2-2-2-6-6 = 6.\n\nТройки: Сумма всех собранных троек. Например: 3-3-1-2-4 = 6.\n\nЧетверки: сумма всех собранных четверок. Например: 4-4-4-5-6 = 12.\n\nПятерки: сумма всех собранных пятерок. Например: 5-5-1-2-3 = 10.\n\nШестерки: сумма всех собранных шестерок. Например: 6-6-6-1-2 = 18.\n\nЛюбая: сумма всех костей, независимо от комбинации. Например: 1-3-3-5-6 = 18.\n\nКороткий стрит: четыре кости, расположенные по порядку. За комбинацию дается 25 очков. Например: 1-2-3-4-1. \n\nДлинный стрит: пять костей, расположенных по порядку. За комбинацию дается 30 очков. Например: 2-3-4-5-6.\n\nФул хауз: две кости одного номинала и три кости другого. Результатом будет сумма всех костей. Например: 2-2-3-3-3 = 13.\n\nКаре: четыре кости одного номинала. Результатом будет сумма всех костей. Например: 5-5-5-5-1 = 21.\n\nПокер: пять костей одного номинала. За комбинацию дается 50 очков. Например: 1-1-1-1-1", "Вернуться"];
  }
}
